finder = "rofi"
preview_length = 80

[rofi]
line_length = 200
menu_length = 15
menu_prompt = "clipboard"

[custom_finder]
program = "bemenu"
args = ["-l 20", "-p clipboard"]

[log]
emit_journald = false
emit_stdout = false
emit_stderr = false
level = "INFO"
